//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlattyTweet.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlattyTweet.Translations.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete direct message.
        /// </summary>
        public static string DeleteDMCaption {
            get {
                return ResourceManager.GetString("DeleteDMCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this direct message? It cannot be recovered..
        /// </summary>
        public static string DeleteDMText {
            get {
                return ResourceManager.GetString("DeleteDMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete tweet.
        /// </summary>
        public static string DeleteTweetCaption {
            get {
                return ResourceManager.GetString("DeleteTweetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tweet? It cannot be recovered..
        /// </summary>
        public static string DeleteTweetText {
            get {
                return ResourceManager.GetString("DeleteTweetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opening link failed.
        /// </summary>
        public static string LinkOpenErrorCaption {
            get {
                return ResourceManager.GetString("LinkOpenErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The browser is not answering our phone calls. We just want to talk.
        ///
        ///Please check the browser for any pending updates and is responding.
        ///
        ///Try opening the link again?.
        /// </summary>
        public static string LinkOpenErrorText {
            get {
                return ResourceManager.GetString("LinkOpenErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Accounts.
        /// </summary>
        public static string ManageAccountsString {
            get {
                return ResourceManager.GetString("ManageAccountsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweet failed.
        /// </summary>
        public static string RetweetErrorCaption {
            get {
                return ResourceManager.GetString("RetweetErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retweeting. This may be because the tweet is from a protected account or it has been deleted..
        /// </summary>
        public static string RetweetErrorText {
            get {
                return ResourceManager.GetString("RetweetErrorText", resourceCulture);
            }
        }
    }
}
